name: "Irrigazione Centralizzata"
description: "Programmazione e controllo dell'irrigazione tramite le entità di Home Assistant"
version: "0.2.0"
slug: "irrigazione_centralizzata"
url: "https://github.com/emaiod/ha-irrigazione"
init: false
startup: application
boot: auto
ingress: true
ingress_port: 8099
ingress_stream: false
panel_icon: "mdi:sprinkler-variant"
panel_title: "Irrigazione"
homeassistant_api: true
arch:
  - aarch64
  - amd64
options: {}
schema: {}
